### PR TITLE
archive 2022 and update and stage 2023 site content

### PR DESCRIPTION
**Pull request by stephlabou**
Archives 2022 content
Adds 2023 folders and template files, with updates as needed
Stages 2023 site home page with "coming soon" info

### CODE REVIEW

**Review by kekoziar — CHANGES_REQUESTED** [review]
`_includes/2022_includes/header-menu.html` needs `/2022/` in the previous years drop down list item, line 34.

**Review by kekoziar — CHANGES_REQUESTED** [review]
The live page calendar (https://github.com/uc-love-data-week/uc-love-data-week.github.io/blob/main/_2022_pages/calendar_js.html) has links to the recordings.  The js_2022 still has registration open, so js_2022 needs to be updated with the contents of main calendar file. I think the whole thing could probably be fixed by putting the javascript into an includes file.  at the time, I was just focused on getting the calendar working, I wasn't thinking about overall organization.  I'll put in an issue for the current year, but for archiving purposes, I think we can just copy the current calendar into the 2022 archived one (with appropriate header changes).

**Comment by stephlabou** [comment]
I've removed js_2022 to just keep the main (https://github.com/uc-love-data-week/uc-love-data-week.github.io/blob/main/_2022_pages/calendar_js.html) and it looks to work as intended: includes links to recordings, but no registration. Will add and commit.

**Comment by stephlabou** [comment]
> `_includes/2022_includes/header-menu.html` needs `/2022/` in the previous years drop down list item, line 34.

Fixed

**Review by kekoziar — APPROVED** [review]
Perfect.  Thanks for the update.  Looks good.  I'll go ahead and merge.

**Pull request merged**
